### Import Library

In [1]:
import numpy as np

## Creating Numpy arrays

### From a python list

In [3]:
lst=[1,2,3,4]
lst

[1, 2, 3, 4]

In [4]:
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [5]:
#Creating 2-D array

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr_2=np.array(my_matrix)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods 
    There are lots of built-in methods to generate Arrays.

### arange
Return evenly spaced values within a given interval.

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To get array of numbers with specific interval



In [16]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Zeros and Ones

In [19]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(shape=3)

array([0., 0., 0.])

In [21]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
#Return a new array of given shape and type, filled with ones.
np.ones(shape=4)

array([1., 1., 1., 1.])

In [23]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.



In [28]:
np.linspace(start=0,stop=10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.linspace(start=0,stop=10,num=50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Return an identity matrix

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random
Numpy also has lots of ways to create random number arrays:



### rand
Random numbers from Uniform Distribution

In [34]:
np.random.rand(3,)

array([0.02041785, 0.4075768 , 0.78257844])

In [35]:
np.random.rand(5,5)

array([[0.60769149, 0.72999412, 0.44582152, 0.50935033, 0.96802261],
       [0.78775984, 0.36742907, 0.24813323, 0.42966196, 0.24865829],
       [0.94361071, 0.02947606, 0.21817163, 0.44339959, 0.38142651],
       [0.62683877, 0.6236788 , 0.67405456, 0.74934584, 0.78574195],
       [0.93160603, 0.2783825 , 0.59034643, 0.45166346, 0.73529199]])

### randn
Random numbers from Gaussian Distribution

In [37]:
np.random.randn(5)

array([-0.84213227, -0.6022814 , -0.2052732 ,  2.26077624, -0.90798858])

In [38]:
np.random.randn(5,5)

array([[-2.27245559,  1.13166194, -0.12107084,  0.61210872,  0.4383178 ],
       [-0.71795612,  1.67560019,  0.45123083,  0.70973222,  0.83672324],
       [-1.5520099 , -0.43682667, -2.17355755,  0.09128413,  0.54667577],
       [-0.89881911,  0.80337   ,  0.51088693,  2.16991813,  0.39942098],
       [ 0.18240418,  1.45038117,  0.69128543, -1.96820823,  1.38382989]])

### randint 
random integers from ``low`` (inclusive) to ``high`` (exclusive).


In [39]:
np.random.randint(0,12)

9

In [43]:
#Create random integers from 0 to 100
np.random.randint(0,100,size=10)

array([24, 17, 64, 58,  5, 48, 57, 74, 13, 88])

### Reshape

In [46]:
arr_1=np.arange(1,26)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [49]:
arr_2=np.random.randint(0,100,10)
arr_2

array([17, 88, 67, 31, 88, 82, 84, 33,  2, 50])

In [51]:
#Returns an array containing the same data with a new shape.
arr_1.reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [52]:
#Return the maximum along a given axis.
arr_2.max()

88

In [53]:
#Return the minimum along a given axis.
arr_2.min()

2

In [55]:
#Return indices of the minimum values along the given axis of `a`.
arr_2.argmin()

8

In [56]:
#Return indices of the maximum values along the given axis.
arr_2.argmax()

1

### Shape
Shape is an attribute that arrays have (not a method):

In [59]:
#1-D array
arr_1.shape

(25,)

In [60]:
#2-D array
arr_1.reshape((5,5)).shape

(5, 5)

### dtype
Grab the data type of the object in the array:

In [63]:
arr_1.dtype

dtype('int64')

### Numpy Indexing and Selection

In [65]:
arr_in = np.arange(0,11)
arr_in

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#Get a value at an index
arr_in[7]

7

In [69]:
#Get values in a range
arr_in[2:6]

array([2, 3, 4, 5])

In [72]:
#To Grab Everything from Start to End
arr_in[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting
Numpy array differs from python list because of their ability to broadcast

In [76]:
#Grabing the particular index and setting up value
arr_in[0:3]=100

arr_in

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [83]:
#Slice of an array
slice_array = arr_in[0:6]

slice_array

array([100, 200, 200, 200, 200, 200])

In [84]:
#Setting value for array
slice_array[:]=200

slice_array

array([200, 200, 200, 200, 200, 200])

In [86]:
#Note Changes also occuring in original array
arr_in

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [87]:
#Return a copy of the array.
arr_copy = arr_in.copy()

arr_copy

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [89]:
arr_copy[2:6]=300

arr_copy

array([200, 200, 300, 300, 300, 300,   6,   7,   8,   9,  10])

In [91]:
#Changes not occuring in original array
arr_in

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

## Indexing a 2-D array (matrices)

The general format is **arr_2d[row,col]** or **arr_2d[row][col]**

In [95]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
#Indexing row

arr_2d[1]

array([4, 5, 6])

In [97]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting 2nd row, 1st value 
arr_2d[1][0]

4

In [98]:
## Getting 2nd row, 1st value 
arr_2d[1,0]

4

In [106]:
#2D array slicing
#shape (2,2) from top right corner

arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [107]:
#Shape bottom row

arr_2d[2]

array([7, 8, 9])

In [109]:
#Shape bottom row

arr_2d[2,:]

array([7, 8, 9])

## Fancy Indexing

In [111]:
arr_new=np.random.randint(0,100,(10,10))

In [113]:
#Fancy indexing allows following
arr_new[[2,4,6,8]]

array([[76, 22, 18, 46, 20, 84, 70, 60, 39, 82],
       [ 5, 88, 85, 69, 73, 24, 38, 18, 20, 49],
       [84, 12, 84, 44, 20, 82,  5, 52, 83, 28],
       [74, 31, 93, 98, 19, 27, 58, 97,  3, 29]])

In [115]:
#Allows any order
arr_new[[6,5,7,4]]

array([[84, 12, 84, 44, 20, 82,  5, 52, 83, 28],
       [11, 27, 51,  0, 34, 11, 48,  2, 36, 77],
       [27, 60,  4, 44, 54,  6, 80, 84, 32, 17],
       [ 5, 88, 85, 69, 73, 24, 38, 18, 20, 49]])

## Array Comparison

In [117]:
arr_3 = np.arange(1,11)

arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
#save bool array
bool_arr=arr_3>4

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

This will return the value where there is 'true' in boolean array


In [122]:
#Conditional Selection
arr_3[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [123]:
x=2
arr_3[arr_3>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Numpy Operations

### Arithmetic Operations

In [126]:
arr_4 = np.arange(10)

arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
#Addition 
arr_4+arr_4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [128]:
#Subraction
arr_4-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [129]:
#Multiplication
arr_4*arr_4

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
#Division
arr_4/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [131]:
#Dividing by zero will give warning not an error
#It will be replaced by nan value
arr_4/arr_4

<ipython-input-131-ab0bb0096271>:1: RuntimeWarning: invalid value encountered in true_divide
  arr_4/arr_4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [133]:
# Also warning, but not an error instead infinity
1/arr_4

<ipython-input-133-13968461f226>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr_4


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [134]:
arr_4 ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array function

In [136]:
#square root
np.sqrt(arr_4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [137]:
#for exponent
np.exp(arr_4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [138]:
#Return maximum
np.max(arr_4)

9

In [140]:
#Trigonometric sine, element-wise.
np.sin(arr_4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [142]:
#Natural logarithm, element-wise.
np.log(arr_4)

<ipython-input-142-00ce72e13963>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr_4)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])